[package] 
name    = "swarm_orchestrator_for_autonomous_learners"
version = "0.1.0"
edition = "2024"

[dependencies]                
bevy         = { version = "0.16.1", features = ["bevy_winit", "png"] }
egui         = "0.32.0"
dirs-next    = "2.0"
toml         = "0.9.2"

[dependencies.bevy_egui]
version      = "0.35.1"

# ────────────────────────────────────────────────────────────────────────────
# Workspace definition
# ────────────────────────────────────────────────────────────────────────────
[workspace]
# Paths are *relative to this file*.
members = [
    "lib/automata",
    "lib/engine_core",
    "lib/io/input",
    "lib/io/output",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json   = "1.0.141"
rand  = "0.9.1"
