[package]
name    = "swarm_orchestrator_for_autonomous_learners"
version = "0.1.0"
edition = "2024"

[dependencies]
# ---------------------------------------------------------------------------
# Core engine
# ---------------------------------------------------------------------------
bevy = { version = "0.16.1", features = ["bevy_winit", "png"] }
egui = "0.32.0"
# ---------------------------------------------------------------------------
# Miscellaneous utilities
# ---------------------------------------------------------------------------
rand        = "0.9.1"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"

# ---------------------------------------------------------------------------
# Immediate‑mode GUI (egui, via Bevy)
# ---------------------------------------------------------------------------
[dependencies.bevy_egui]
version          = "0.35.1"

